// autogenerated

import { defineConfigWithDefaults } from '@alexaegis/vite';
import dts from 'vite-plugin-dts';
import { autolib } from './src/index.js';

export default defineConfigWithDefaults({
	plugins: [
		autolib(),
		dts({
			entryRoot: 'src',
			copyDtsFiles: true,
		}),
	],
});
